import runpy
import numpy as np
from collections import deque

P = 3
ROOT = 'research/'

# A3-4-14 is the verified source for the 35D B/A and K generator actions.
ns = runpy.run_path(ROOT + 'A3-4-14_BA_MODULE_FINGERPRINT_2026-09-16.py')
rank3 = ns['rank3']
Mgens = [np.array(M, dtype=np.int64) % P for M in ns['Mgens']]
BA_gens = [np.array(T, dtype=np.int64) % P for T in ns['BA']]
K_gens = [np.array(T, dtype=np.int64) % P for T in ns['K']]

assert len(Mgens) == 5 and len(BA_gens) == 5 and len(K_gens) == 5
assert all(T.shape == (35, 35) for T in BA_gens + K_gens)
assert all(rank3(T) == 35 for T in BA_gens + K_gens)

I4 = np.eye(4, dtype=np.int64)
I35 = np.eye(35, dtype=np.int64)

def mm(A, B):
    return (A @ B) % P

def key(M):
    return tuple(int(x) for x in M.reshape(-1))

def inv4(M):
    # 4x4 inverse over F_3 by exact Gauss-Jordan.
    R = np.column_stack([M.copy() % P, I4.copy()])
    r = 0
    for c in range(4):
        q = next(i for i in range(r, 4) if R[i, c])
        R[[r, q]] = R[[q, r]]
        if R[r, c] == 2:
            R[r] = (2 * R[r]) % P
        for i in range(4):
            if i != r and R[i, c]:
                R[i] = (R[i] - R[i, c] * R[r]) % P
        r += 1
    return R[:, 4:] % P

Ginv = [inv4(G) for G in Mgens]
assert all(np.array_equal(mm(G, Gi), I4) for G, Gi in zip(Mgens, Ginv))

# ---------- Enumerate H generated by the five verified matrices ----------
Gmap = {key(I4): 0}
group = [I4]
parent = [-1]
parent_gen = [-1]
q = deque([0])
while q:
    i = q.popleft()
    A = group[i]
    for gi, G in enumerate(Mgens):
        H = mm(A, G)
        k = key(H)
        if k not in Gmap:
            idx = len(group)
            Gmap[k] = idx
            group.append(H)
            parent.append(i)
            parent_gen.append(gi)
            q.append(idx)

print('A3-4-15 / CLASS-LEVEL MODULE COMPARISON')
print('Enumerated group size =', len(group))
assert len(group) == 51840

# ---------- Conjugacy classes ----------
# Conjugation by generators and their inverses is sufficient because they
# generate H.  Store only the resulting index adjacency.
adj = [[] for _ in range(len(group))]
for i, A in enumerate(group):
    for G, Gi in zip(Mgens, Ginv):
        adj[i].append(Gmap[key(mm(mm(G, A), Gi))])
        adj[i].append(Gmap[key(mm(mm(Gi, A), G))])

seen = np.zeros(len(group), dtype=bool)
classes = []
class_of = np.full(len(group), -1, dtype=np.int32)
for start in range(len(group)):
    if seen[start]:
        continue
    stack = [start]
    seen[start] = True
    cls = []
    while stack:
        i = stack.pop()
        cls.append(i)
        for j in adj[i]:
            if not seen[j]:
                seen[j] = True
                stack.append(j)
    ci = len(classes)
    for i in cls:
        class_of[i] = ci
    classes.append(cls)

print('Conjugacy class count =', len(classes))
assert sum(len(c) for c in classes) == 51840

# ---------- Generator words and induced 35D actions ----------
def word_for(idx):
    w = []
    while parent[idx] != -1:
        w.append(parent_gen[idx])
        idx = parent[idx]
    return list(reversed(w))

def rep_from_word(word, mats):
    R = I35.copy()
    for gi in word:
        R = (R @ mats[gi]) % P
    return R

def mat_order(T, max_order=200):
    R = np.eye(T.shape[0], dtype=np.int64)
    for k in range(1, max_order + 1):
        R = (R @ T) % P
        if np.array_equal(R, np.eye(T.shape[0], dtype=np.int64)):
            return k
    return None

def fingerprint(T):
    D = (T - I35) % P
    ranks = []
    R = D.copy()
    for _ in range(12):
        r = rank3(R)
        ranks.append(r)
        if r == 0:
            break
        R = (R @ D) % P
    return {
        'trace_F3': int(np.trace(T) % P),
        'order': mat_order(T),
        'fixed_dim': 35 - rank3(D),
        'rank(T-I)': rank3(D),
        'ranks_powers': ranks,
    }

rows = []
for ci, cls in enumerate(classes, 1):
    rep_idx = min(cls)
    word = word_for(rep_idx)
    rep = group[rep_idx]
    Tb = rep_from_word(word, BA_gens)
    Tk = rep_from_word(word, K_gens)
    fb = fingerprint(Tb)
    fk = fingerprint(Tk)
    rows.append((ci, len(cls), rep, word, fb, fk))

print('class | size | group_order | word_length | BA trace/order/fix/rank | K trace/order/fix/rank | equal')
for ci, size, rep, word, fb, fk in rows:
    print(ci, '|', size, '|', mat_order(rep), '|', len(word), '|',
          fb['trace_F3'], fb['order'], fb['fixed_dim'], fb['rank(T-I)'], '|',
          fk['trace_F3'], fk['order'], fk['fixed_dim'], fk['rank(T-I)'], '|',
          fb == fk)

diff = [r for r in rows if r[4] != r[5]]
print()
print('DISTINGUISHING_CLASS_COUNT =', len(diff))
for ci, size, rep, word, fb, fk in diff:
    print('DISTINGUISHING CLASS', ci,
          'size=', size,
          'group_order=', mat_order(rep),
          'word=', word)
    print('  B/A =', fb)
    print('  K   =', fk)

for gi, G in enumerate(Mgens, 1):
    idx = Gmap[key(G)]
    print('ORIGINAL_GENERATOR_CLASS', gi, '=', int(class_of[idx]) + 1,
          'order=', mat_order(G))

print('RESULT: class-level comparison completed.')
print('NOTE: traces are reported in F_3; no ordinary-character classification in defining characteristic is claimed.')
print('ALL A3-4-15 CHECKS COMPLETED')
