"""Gate 0-B Q1: independent q=infinity pure-commutator degree-4 calculation.

This stage computes the relation filtration recursively from the common
quadratic relation R=[X1,X2]+[X3,X4], with no q=3 restricted-power term.
It reports dim (R_inf)_3, dim (R_inf)_4 and dim Q4_inf=L4/(R_inf)_4.
"""
from itertools import product

P = 3
n_gen = 4


def rank3(A):
    A=[list(map(lambda x:int(x)%P,row)) for row in A]
    m=len(A); n=len(A[0]) if m else 0; r=0
    for c in range(n):
        q=next((i for i in range(r,m) if A[i][c]),None)
        if q is None: continue
        A[r],A[q]=A[q],A[r]
        inv=1 if A[r][c]==1 else 2
        A[r]=[(inv*x)%P for x in A[r]]
        for i in range(m):
            if i!=r and A[i][c]:
                f=A[i][c]
                A[i]=[(A[i][j]-f*A[r][j])%P for j in range(n)]
        r+=1
        if r==m: break
    return r

# Degree-d associative words. Lie subspaces are represented in the full
# tensor algebra; brackets with generators are exact linear maps.
def words(d):
    return list(product(range(1,n_gen+1), repeat=d))

idx={d:{w:i for i,w in enumerate(words(d))} for d in range(2,5)}

def bracket_right(v,d,g):
    # [v,X_g] = v X_g - X_g v
    out=[0]*(n_gen**(d+1))
    idx_next=idx[d+1]
    for j,c in enumerate(v):
        c%=P
        if c:
            w=words(d)[j]
            out[idx_next[w+(g,)]]=(out[idx_next[w+(g,)]]+c)%P
            out[idx_next[(g,)+w]]=(out[idx_next[(g,)+w]]-c)%P
    return out

# q=infinity quadratic relation, independently encoded.
w2=words(2)
vR=[0]*len(w2)
vR[w2.index((1,2))]=1
vR[w2.index((2,1))]=2
vR[w2.index((3,4))]=1
vR[w2.index((4,3))]=2

# (R_inf)_3 = [L1,R] and (R_inf)_4=[L1,(R_inf)_3].
R3=[]
for g in range(1,5): R3.append(bracket_right(vR,2,g))
R3_mat=[R3[i] for i in range(4)]

R4=[]
for v in R3_mat:
    for g in range(1,5): R4.append(bracket_right(v,3,g))

L4_words=words(4)
# Degree-4 free Lie space is generated by all iterated brackets of degree 3
# Lie words with one generator. Construct L3 first, then bracket with X_g,
# and also use all degree-4 left-normed commutators generated recursively.
# For this Demushkin relation calculation the quotient dimension is obtained
# inside L4, so construct L_d by the same bracket recursion from L_{d-1}.
L2=[]
for a in range(1,5):
    for b in range(a+1,5):
        v=[0]*len(w2); v[w2.index((a,b))]=1; v[w2.index((b,a))]=2; L2.append(v)
L3=[]
for v in L2:
    for g in range(1,5): L3.append(bracket_right(v,2,g))
L4=[]
for v in L3:
    for g in range(1,5): L4.append(bracket_right(v,3,g))

dimL4=rank3(L4)
dimR3=rank3(R3)
dimR4=rank3(R4)

# R4 is contained in L4; quotient dimension is dim L4 - dim R4.
# Also verify containment by rank([L4 | R4]).
containment=rank3(L4+R4)==dimL4
qdim=dimL4-dimR4

print("GATE0B_Q1_QINF_DEGREE4")
print("relation R_inf = [X1,X2]+[X3,X4]")
print("dim (R_inf)_3 =",dimR3)
print("dim (R_inf)_4 =",dimR4)
print("dim L4 =",dimL4)
print("dim Q4_inf =",qdim)
print("R4 subset L4 =",containment)
print("RESULT =", "PASS" if containment else "FAIL")

assert containment
