# O2-2S: verify that the uniquely solved obstruction block actions T_g
# define a well-defined representation of the generated Sp4(F3) group.
# Instead of guessing a presentation, enumerate the actual generated group and
# check that every collision of words in the 4x4 generator action has the same
# T-image. This is stronger and convention-safe.
import runpy
import numpy as np
from collections import deque

P = 3
ROOT = 'research/'


def key(M):
    return bytes((np.array(M, dtype=np.int64) % P).astype(np.uint8).reshape(-1).tolist())


def inv3(A):
    A = np.array(A, dtype=np.int64) % P
    n = A.shape[0]
    R = np.concatenate([A, np.eye(n, dtype=np.int64)], axis=1) % P
    r = 0
    for c in range(n):
        q = next((i for i in range(r, n) if R[i, c]), None)
        if q is None:
            return None
        R[[r, q]] = R[[q, r]]
        if R[r, c] == 2:
            R[r] = (2 * R[r]) % P
        for i in range(n):
            if i != r and R[i, c]:
                R[i] = (R[i] - R[i, c] * R[r]) % P
        r += 1
    return R[:, n:] % P

# Recompute the unique T_g from O2-2R.
o2r = runpy.run_path(ROOT + 'O2-2R_OBSTRUCTION_EQUIVARIANCE_2026-09-18.py')
T = [np.array(x, dtype=np.int64) % P for x in o2r['solutions']]
assert len(T) == 5 and all(x.shape == (4, 4) for x in T)

# Exact original generator matrices, same order as T.
san = runpy.run_path(ROOT + 'A3_4_10_BRACKET_PIPELINE_SANITY_2026-09-17.py')
gens = [np.array(g, dtype=np.int64) % P for g in san['gens']]
assert len(gens) == 5 and all(g.shape == (4, 4) for g in gens)

# The five transvections have order 3, so g^{-1}=g^2. We nevertheless compute
# inverses explicitly to avoid assuming this in the consistency test.
gens_inv = []
T_inv = []
for i, (g, t) in enumerate(zip(gens, T)):
    gi = inv3(g)
    ti = inv3(t)
    assert gi is not None and ti is not None
    assert np.array_equal((g @ gi) % P, np.eye(4, dtype=np.int64))
    assert np.array_equal((t @ ti) % P, np.eye(4, dtype=np.int64))
    gens_inv.append(gi)
    T_inv.append(ti)
    print('GENERATOR', i, 'T invertible =', True)

# Enumerate the subgroup generated by the five exact generators. For every
# group element, store the T-image obtained by the first word reaching it.
# Whenever another word reaches the same group element, its T-image must agree.
# This tests all relations of the generated finite group, not merely a chosen
# presentation.
I4 = np.eye(4, dtype=np.int64)
seen = {key(I4): I4.copy()}
timage = {key(I4): I4.copy()}
queue = deque([I4])
steps = [(gens[i], T[i], i, '+') for i in range(5)] + [(gens_inv[i], T_inv[i], i, '-') for i in range(5)]
collision_count = 0
mismatch_count = 0
first_mismatch = None

while queue:
    A = queue.popleft()
    ka = key(A)
    TA = timage[ka]
    for G, TG, gi, sign in steps:
        B = (A @ G) % P
        TB = (TA @ TG) % P
        kb = key(B)
        if kb not in seen:
            seen[kb] = B
            timage[kb] = TB
            queue.append(B)
        else:
            collision_count += 1
            if not np.array_equal(timage[kb], TB):
                mismatch_count += 1
                if first_mismatch is None:
                    first_mismatch = (A.copy(), G.copy(), TB.copy(), timage[kb].copy(), gi, sign)

print('O2-2S: OBSTRUCTION T-GROUP CONSISTENCY')
print('generated group order =', len(seen))
print('expected Sp4(F3) order = 51840')
print('word collisions checked =', collision_count)
print('inconsistent T-images =', mismatch_count)

if first_mismatch is not None:
    A, G, got, expected, gi, sign = first_mismatch
    print('FIRST_MISMATCH generator =', gi, 'sign =', sign)
    print('computed T-image =')
    print(got)
    print('stored T-image =')
    print(expected)

GROUP_ORDER_PASS = (len(seen) == 51840)
CONSISTENCY_PASS = (mismatch_count == 0)
PASS = GROUP_ORDER_PASS and CONSISTENCY_PASS

print('GENERATED_GROUP_ORDER_51840 =', GROUP_ORDER_PASS)
print('ALL_GROUP_RELATIONS_RESPECTED_BY_T =', CONSISTENCY_PASS)
print('O2-2S PASS =', PASS)

if not PASS:
    raise AssertionError('O2-2S FAIL: T does not define the required well-defined action on the generated group')

print('CONCLUSION: the unique generator-level T_g from O2-2R descends to a well-defined 4-dimensional representation of the generated Sp4(F3) group.')
