#!/usr/bin/env python3
"""Paper5 Gate B B4 p=3: nontrivial diagonal a=2 through D9.
Exact truncated associative Magnus algebra over F3.
Checks the zero-correction path W=z^2 against the full two-sided ideal
generated by r-1, degree by degree. LOCAL diagnostic, not pro-p closure.
"""
from itertools import product
from math import comb

P=3
LETTERS=("X","Y","Z")
DIG={"X":0,"Y":1,"Z":2}

def add(a,b):
    c=dict(a)
    for w,v in b.items():
        c[w]=(c.get(w,0)+v)%P
        if not c[w]: c.pop(w,None)
    return c

def sc(a,s):
    return {w:(v*s)%P for w,v in a.items() if (v*s)%P}

def mul(a,b,N):
    c={}
    for u,cu in a.items():
        for v,cv in b.items():
            if len(u)+len(v)<=N:
                c[u+v]=(c.get(u+v,0)+cu*cv)%P
    return {w:v for w,v in c.items() if v}

def pw(a,n,N):
    out={():1}; q=a
    while n:
        if n&1: out=mul(out,q,N)
        n//=2
        if n: q=mul(q,q,N)
    return out

def onepow(ch,n,N):
    out={}
    for k in range(N+1):
        if n>=0 and k>n: continue
        coef=comb(n,k) if n>=0 else (-1)**k*comb(-n+k-1,k)
        if coef%P: out[(ch,)*k]=coef%P
    return out

def inv(a,N):
    h=add(a,{():-1}); out={():1}; q={():1}
    for _ in range(N):
        q=mul(q,sc(h,-1),N); out=add(out,q)
    return out

def hom(a,d):
    return {w:c for w,c in a.items() if len(w)==d}

ONE={():1}; X={("X",):1}; Y={("Y",):1}; Z={("Z",):1}

def membership(N, high=False):
    x=add(ONE,X); y=add(ONE,Y); z=add(ONE,Z)
    a=2
    comm=mul(mul(mul(onepow("X",-1,N),onepow("Y",-1,N),N),x,N),y,N)
    r=add(mul(mul(onepow("Z",3,N),onepow("X",-3,N),N),inv(comm,N),N),sc(ONE,-1))
    xa=pw(x,a,N)
    comm_a=mul(mul(mul(onepow("X",-a,N),onepow("Y",-1,N),N),xa,N),y,N)
    target=add(mul(pw(x,3*a,N),comm_a,N),sc(ONE,-1))
    # W=z^a=z^2. q is the degree-N part of W^3-X_a.
    q=hom(add(pw(pw(z,a,N),3,N),sc(target,-1)),N)

    RH={d:hom(r,d) for d in range(2,N+1)}
    D=3**N; MASK=(1<<D)-1

    def padd(a,b):
        al,ah=a; bl,bh=b
        lo=(((al^bl)&~(ah|bh))|(ah&bh))&MASK
        hi=(((ah^bh)&~(al|bl))|(al&bl))&MASK
        return lo,hi

    def pneg(a): return a[1],a[0]

    def idx(w):
        q=0
        for ch in w: q=q*3+DIG[ch]
        return q

    def prow(poly):
        lo=hi=0
        for w,c in poly.items():
            bit=1<<idx(w)
            if c==1: lo|=bit
            elif c==2: hi|=bit
        return lo,hi

    basis={}
    def insert(row):
        while row!=(0,0):
            lo,hi=row
            nz=lo|hi
            bit=(1<<(nz.bit_length()-1)) if high else (nz&-nz)
            p=bit.bit_length()-1
            old=basis.get(p)
            if old is None:
                if hi&bit: row=pneg(row)
                basis[p]=row
                return
            row=padd(row,pneg(old) if lo&bit else old)

    generators=0
    for d in range(2,N+1):
        h=RH[d]; rem=N-d
        for i in range(rem+1):
            for u in product(LETTERS,repeat=i):
                for v in product(LETTERS,repeat=rem-i):
                    insert(prow({u+w+v:c for w,c in h.items()}))
                    generators+=1

    row=prow(q)
    while row!=(0,0):
        lo,hi=row; nz=lo|hi
        bit=(1<<(nz.bit_length()-1)) if high else (nz&-nz)
        p=bit.bit_length()-1
        old=basis.get(p)
        if old is None: break
        row=padd(row,pneg(old) if lo&bit else old)

    return len(basis),generators,len(q),row==(0,0)

print("Paper5 Gate B B4 p=3, a=2, zero-correction W=z^2")
results=[]
for N in range(4,10):
    lo=membership(N,high=False)
    hi=membership(N,high=True)
    assert lo==hi, (N,lo,hi)
    results.append((N,lo))
    rank,gens,qterms,ok=lo
    print(f"D{N}: ideal_rank={rank} generators={gens} q_terms={qterms} member={ok}")
print("STATUS=PASS_LOCAL_THROUGH_D9")
print("INDEPENDENT_PIVOT_CHECK=PASS")
