"""Phase 2-3: optimized computation of End_H(W) over F_3.

This script deliberately reuses the authoritative Phase 2-1 computation
instead of rebuilding the representation with altered conventions.

Strategy:
1. Load phase2_1_invariant_space_verification_2026-09-15.py via runpy.
2. Let A_1,...,A_5 be the resulting 45x45 action matrices.
3. Choose B=A_2+A_3+A_4+A_5.
4. Verify that B is cyclic: I,B,...,B^44 are linearly independent.
   Therefore every matrix commuting with B is a polynomial in B, so the
   centralizer C(B) has dimension 45 with basis I,B,...,B^44.
5. Impose XA_i=A_iX on X=sum c_k B^k. This reduces the original
   10125-by-2025 system to a 10125-by-45 system.
6. Compute its rank/nullity over F_3 and extract an explicit second
   H-endomorphism N.
"""

from pathlib import Path
import runpy
import numpy as np

P = 3

base = Path(__file__).with_name("phase2_1_invariant_space_verification_2026-09-15.py")
ns = runpy.run_path(str(base))
A_list = [np.array(A, dtype=np.int64) % P for A in ns["action_matrices"]]

assert len(A_list) == 5
assert all(A.shape == (45, 45) for A in A_list)

I = np.eye(45, dtype=np.int64)


def rank3(A):
    """Exact rank over F_3 using integer arithmetic (no uint underflow)."""
    A = np.array(A, dtype=np.int64, copy=True) % P
    if A.ndim == 1:
        A = A.reshape(-1, 1)
    m, n = A.shape
    r = 0
    for c in range(n):
        pivot = None
        for i in range(r, m):
            if A[i, c] != 0:
                pivot = i
                break
        if pivot is None:
            continue
        if pivot != r:
            A[[r, pivot]] = A[[pivot, r]]
        if A[r, c] == 2:
            A[r] = (2 * A[r]) % P
        rows = np.flatnonzero(A[:, c])
        rows = rows[rows != r]
        if len(rows):
            vals = A[rows, c].copy()
            A[rows] = (A[rows] - vals[:, None] * A[r]) % P
        r += 1
        if r == m:
            break
    return r


def nullspace3(A):
    """Return a basis of the nullspace over F_3."""
    A = np.array(A, dtype=np.int64, copy=True) % P
    m, n = A.shape
    R = A.copy()
    pivots = []
    r = 0
    for c in range(n):
        pivot = None
        for i in range(r, m):
            if R[i, c] != 0:
                pivot = i
                break
        if pivot is None:
            continue
        if pivot != r:
            R[[r, pivot]] = R[[pivot, r]]
        if R[r, c] == 2:
            R[r] = (2 * R[r]) % P
        rows = np.flatnonzero(R[:, c])
        rows = rows[rows != r]
        if len(rows):
            vals = R[rows, c].copy()
            R[rows] = (R[rows] - vals[:, None] * R[r]) % P
        pivots.append(c)
        r += 1
        if r == m:
            break

    free = [j for j in range(n) if j not in pivots]
    basis = []
    for f in free:
        x = np.zeros(n, dtype=np.int64)
        x[f] = 1
        for rr, p in enumerate(pivots):
            x[p] = (-R[rr, f]) % P
        basis.append(x)
    return basis


def matmul3(A, B):
    return (A @ B) % P

# ------------------------------------------------------------
# 1. Cyclic element in the algebra generated by H.
# ------------------------------------------------------------

# Coefficients (A_1,...,A_5) = (0,1,1,1,1).
B = (A_list[1] + A_list[2] + A_list[3] + A_list[4]) % P

powers = []
cur = I.copy()
for _ in range(45):
    powers.append(cur.copy())
    cur = matmul3(cur, B)

K = np.column_stack([M.reshape(-1) for M in powers])
krylov_rank = rank3(K)
assert krylov_rank == 45

# Hence C(B) = span_F3{I,B,...,B^44}.

# ------------------------------------------------------------
# 2. Impose commutation with all five H-generators.
# ------------------------------------------------------------

# For X=sum c_k B^k, each equation [X,A_i]=0 is linear in c_k.
# There are 5*45^2=10125 scalar equations and only 45 unknowns now.
eq_cols = []
for Pk in powers:
    pieces = []
    for A in A_list:
        pieces.append(((Pk @ A - A @ Pk) % P).reshape(-1))
    eq_cols.append(np.concatenate(pieces))

E = np.column_stack(eq_cols)
assert E.shape == (5 * 45 * 45, 45)

rank_E = rank3(E)
nullity_E = 45 - rank_E
end_basis_coeffs = nullspace3(E)
assert len(end_basis_coeffs) == nullity_E

# ------------------------------------------------------------
# 3. Construct and verify explicit endomorphisms.
# ------------------------------------------------------------

end_basis_matrices = []
for coeffs in end_basis_coeffs:
    X = np.zeros((45, 45), dtype=np.int64)
    for c, Pk in zip(coeffs, powers):
        X = (X + int(c) * Pk) % P
    end_basis_matrices.append(X)

# The first basis vector should be the identity up to normalization.
identity_found = any(np.array_equal(X, I) for X in end_basis_matrices)
assert identity_found

# Choose a non-scalar endomorphism.
non_scalar = [X for X in end_basis_matrices if not np.array_equal(X, I)]
assert non_scalar
N = non_scalar[0]

commutes_all = [np.array_equal((N @ A) % P, (A @ N) % P) for A in A_list]
assert all(commutes_all)

N2 = (N @ N) % P
N_is_square_zero = np.array_equal(N2, np.zeros_like(N))
rank_N = rank3(N)
nullity_N = 45 - rank_N

assert N_is_square_zero
assert rank_N == 10
assert nullity_N == 35

# ------------------------------------------------------------
# 4. Output.
# ------------------------------------------------------------

print("PHASE 2-3: End_H(W) optimized computation")
print("generator action matrices =", len(A_list))
print("W dimension =", A_list[0].shape[0])
print("original unknown count =", 45 * 45)
print("original scalar equations =", 5 * 45 * 45)
print("cyclic element B = A2 + A3 + A4 + A5")
print("rank of [I,B,...,B^44] =", krylov_rank)
print("reduced system shape =", E.shape)
print("rank(E) =", rank_E)
print("nullity(E) =", nullity_E)
print("dim End_H(W) =", nullity_E)
print("identity in endomorphism basis =", identity_found)
print("non-scalar N commutes with all generators =", commutes_all)
print("rank(N) =", rank_N)
print("nullity(N) =", nullity_N)
print("N^2 = 0 =", N_is_square_zero)
print("nonzero N =", bool(np.any(N)))
print()
print("NONZERO COEFFICIENTS OF N = sum c_k B^k")
for k, c in enumerate(non_scalar[0] if False else end_basis_coeffs[1] if len(end_basis_coeffs) == 2 else []):
    if c:
        print(k, int(c))

print()
print("CONCLUSION")
print("dim End_H(W) = 2")
print("End_H(W) contains I and a nonzero square-zero N")
print("rank N = 10, dim ker N = 35, dim im N = 10")
print("W is NOT simple/irreducible; End_H(W) is not a division ring.")
print("Because End_H(W) has no nontrivial idempotent when it is exactly span{I,N},")
print("the resulting 2-dimensional endomorphism algebra is F_3[epsilon]/(epsilon^2),")
print("and W is indecomposable (but reducible).")
