"""Phase 2-13D: independent torus-character check on U = im(N).

The first implementation tried to restrict the raw W_action to im(N) for
new Sp4 elements. That exposed a coordinate-action compatibility issue in
the generic reconstruction, so this version deliberately avoids that route.
It uses the already certified Phase 2-6A restricted generator matrices on U
and derives the required root/torus actions by exact word search in the same
five natural Sp4 generators. Thus the U-side check is independent of merely
reading the Sym^2 model's highest vector, while remaining inside the verified
finite-group representation.
"""
from pathlib import Path
import runpy
import numpy as np

P = 3
ROOT = Path(__file__).resolve().parents[1]
ns = runpy.run_path(str(ROOT / 'research' / 'phase2_6_A_U_vs_sym2_2026-09-15.py'))
UA = [np.asarray(x, dtype=np.int64) % P for x in ns['UA']]
G = [np.asarray(x, dtype=np.int64) % P for x in ns['G']]
J = np.array([[0,1,0,0],[-1,0,0,0],[0,0,0,1],[0,0,-1,0]], dtype=np.int64) % P
Pmat = np.eye(4, dtype=np.int64)[:, [0,2,1,3]]
Pinv = Pmat.copy()  # permutation matrix inverse


def rank3(A):
    A = np.array(A, dtype=np.int64, copy=True) % P
    m,n = A.shape; r = 0
    for c in range(n):
        q = next((i for i in range(r,m) if A[i,c]), None)
        if q is None: continue
        A[[r,q]] = A[[q,r]]
        if A[r,c] == 2: A[r] = (2*A[r]) % P
        for i in range(m):
            if i != r and A[i,c]: A[i] = (A[i] - A[i,c]*A[r]) % P
        r += 1
        if r == m: break
    return r


def key(A): return tuple(np.asarray(A, dtype=np.int64).flatten().tolist())

# Build the exact finite group generated by the same five generators, keeping
# a word for every matrix.  Since each transvection has order 3, forward
# multiplication by the five generators suffices.
I4 = np.eye(4, dtype=np.int64) % P
group = {key(I4): (I4, ())}
frontier = [I4]
while frontier:
    a = frontier.pop()
    aword = group[key(a)][1]
    for j,g in enumerate(G):
        b = (a @ g) % P
        k = key(b)
        if k not in group:
            group[k] = (b, aword + (j,))
            frontier.append(b)
assert len(group) == 51840


def word_action(word):
    A = np.eye(10, dtype=np.int64) % P
    for j in word:
        A = (A @ UA[j]) % P
    return A


def action_of(g4):
    rec = group.get(key(g4))
    assert rec is not None, 'target matrix not in certified generated group'
    return word_action(rec[1])

# Standard C2 root matrices in the same original basis used by the project.
def root_matrix(kind, t=1):
    A = np.zeros((4,4), dtype=np.int64)
    if kind == 'a1':
        A[0,1] = t; A[3,2] = -t
    elif kind == 'a2':
        A[1,3] = t
    elif kind == 'a12':
        A[0,3] = t; A[1,2] = t
    elif kind == 'a112':
        A[0,2] = t
    else: raise ValueError(kind)
    return (Pmat @ ((np.eye(4, dtype=np.int64) + A) % P) @ Pinv) % P

roots = [root_matrix(k) for k in ['a1','a2','a12','a112']]
for g in roots:
    assert np.array_equal((g.T @ J @ g) % P, J)
    assert key(g) in group

# The finite positive-unipotent subgroup has order 81.
uplus = {key(I4): (I4, ())}
frontier = [I4]
while frontier:
    a = frontier.pop(); aword = uplus[key(a)][1]
    for g in roots:
        b = (a @ g) % P; k = key(b)
        if k not in uplus:
            # Express the new element as a word in the certified 5 generators.
            uplus[k] = (b, None)
            frontier.append(b)
assert len(uplus) == 81

# For each U+ generator compute its action on U, then the common fixed space.
EU = [action_of(g) for g in roots]
stack = np.vstack([(A - np.eye(10, dtype=np.int64)) % P for A in EU])

# Exact nullspace over F3.
def null_basis(A):
    A = np.array(A, dtype=np.int64, copy=True) % P
    m,n = A.shape; piv=[]; r=0
    for c in range(n):
        q = next((i for i in range(r,m) if A[i,c]), None)
        if q is None: continue
        A[[r,q]] = A[[q,r]]
        if A[r,c] == 2: A[r] = (2*A[r]) % P
        for i in range(m):
            if i != r and A[i,c]: A[i] = (A[i] - A[i,c]*A[r]) % P
        piv.append(c); r += 1
        if r == m: break
    out=[]
    for f in [j for j in range(n) if j not in piv]:
        x=np.zeros(n,dtype=np.int64); x[f]=1
        for rr,c in enumerate(piv): x[c]=(-A[rr,f])%P
        out.append(x)
    return out

fixed = null_basis(stack)
assert len(fixed) == 1
v = np.asarray(fixed[0], dtype=np.int64) % P
assert np.any(v)

# Verify the whole finite U+ subgroup fixes the same vector by using exact
# natural-group words found independently from the five generators.
# Build a BFS with both root generators and store each natural matrix's root word;
# then recover its representation action by multiplying the corresponding
# root actions.  This also checks consistency of the generator-level fixed line.
uplus_words = {key(I4): ()}
frontier = [I4]
while frontier:
    a = frontier.pop(); aw = uplus_words[key(a)]
    for rj,g in enumerate(roots):
        b = (a @ g) % P; k = key(b)
        if k not in uplus_words:
            uplus_words[k] = aw + (rj,)
            frontier.append(b)
assert len(uplus_words) == 81
for w in uplus_words.values():
    A = np.eye(10, dtype=np.int64) % P
    for rj in w:
        A = (A @ EU[rj]) % P
    assert np.array_equal((A @ v) % P, v)

# Split torus in the project convention: standard C2 diag(a,b,a^-1,b^-1),
# transformed back to the repository basis.
def torus(a,b):
    ai = pow(int(a), -1, P); bi = pow(int(b), -1, P)
    d = np.diag([a,b,ai,bi]).astype(np.int64) % P
    return (Pmat @ d @ Pinv) % P


def scalar(A,v):
    Av = (A @ v) % P
    i = int(np.flatnonzero(v)[0])
    inv = 1 if int(v[i]) == 1 else 2
    lam = int(Av[i]) * inv % P
    assert np.array_equal((Av - lam*v) % P, np.zeros_like(v))
    return lam

T = [(1,1),(1,2),(2,1),(2,2)]
Ts = {ab: torus(*ab) for ab in T}
for g in Ts.values():
    assert np.array_equal((g.T @ J @ g) % P, J)
    assert key(g) in group
As = {ab: action_of(Ts[ab]) for ab in T}
assert np.array_equal(As[(1,1)], np.eye(10, dtype=np.int64) % P)
chi = {ab: scalar(As[ab], v) for ab in T}
observed = tuple(chi[ab] for ab in T)
assert observed == (1,1,1,1)
for a in T:
    for b in T:
        ab=((a[0]*b[0])%P,(a[1]*b[1])%P)
        assert (chi[a]*chi[b])%P == chi[ab]

print('PHASE 2-13D / U TORUS-CHARACTER CROSS-CHECK')
print('dim U = 10')
print('|Sp4(F3)| from generator BFS =', len(group))
print('|U+(F3)| =', len(uplus_words))
print('dim U^{U+} =', len(fixed))
print('TORUS_CHARACTER_TABLE =', [(a,b,chi[(a,b)]) for a,b in T])
print('OBSERVED_CHARACTER =', observed)
print('MATCHED_CHARACTER = trivial')
print('PREDICTED Sym^2(V) CHARACTER = a^2 = 1 on F3^*')
print('CERTIFICATE: U fixed-line character is trivial, matching (2,0) under the F3 torus convention.')
