"""Phase 2-13: direct structural probe of E=W/U.

Do not assume a named 35-dimensional module. Recover the H-action on E,
then test invariant subspaces generated by candidate highest-weight vectors.

The first probe is the common fixed space of the positive-root/unipotent
operators, implemented here using the four standard upper-unitriangular
root elements of Sp4(F3) generated from the symplectic transvection model.
This is a discovery computation, not by itself a proof of a highest-weight
classification. Any candidate found here must be verified independently.
"""
from pathlib import Path
import runpy
import numpy as np

P=3
ROOT=Path(__file__).resolve().parents[1]

def r3(A):
    A=np.array(A,dtype=np.int64,copy=True)%P
    m,n=A.shape; r=0
    for c in range(n):
        q=next((i for i in range(r,m) if A[i,c]),None)
        if q is None: continue
        A[[r,q]]=A[[q,r]]
        if A[r,c]==2: A[r]=(2*A[r])%P
        for i in range(m):
            if i!=r and A[i,c]: A[i]=(A[i]-A[i,c]*A[r])%P
        r+=1
        if r==m: break
    return r

def null_basis(A):
    A=np.array(A,dtype=np.int64,copy=True)%P
    m,n=A.shape; R=A.copy(); piv=[]; row=0
    for c in range(n):
        q=next((i for i in range(row,m) if R[i,c]),None)
        if q is None: continue
        R[[row,q]]=R[[q,row]]
        if R[row,c]==2: R[row]=(2*R[row])%P
        for i in range(m):
            if i!=row and R[i,c]: R[i]=(R[i]-R[i,c]*R[row])%P
        piv.append(c); row+=1
        if row==m: break
    free=[c for c in range(n) if c not in piv]
    out=[]
    for f in free:
        x=np.zeros(n,dtype=np.int64); x[f]=1
        for rr,c in enumerate(piv): x[c]=(-R[rr,f])%P
        out.append(x)
    return out

def quotient_action(A,N):
    # Build U=im N, extend to a basis of W, then read the lower-right
    # quotient block. This is the same quotient construction used earlier.
    Ucols=[]; B=np.zeros((45,0),dtype=np.int64); rk=0
    for j in range(45):
        C=np.column_stack([B,N[:,j]])
        q=r3(C)
        if q>rk: B=C; rk=q
        if rk==10: break
    assert rk==10
    for j in range(45):
        C=np.column_stack([B,np.eye(45,dtype=np.int64)[:,j]])
        q=r3(C)
        if q>rk: B=C; rk=q
        if rk==45: break
    # Solve coordinates using full basis via selected independent rows.
    rows=[]; R=np.empty((0,45),dtype=np.int64); rr=0
    for i in range(45):
        C=np.vstack([R,B[i:i+1]])
        q=r3(C)
        if q>rr: R=C; rows.append(i); rr=q
        if rr==45: break
    out=[]
    Br=B[rows]
    for g in A:
        X=(g@B)%P
        AX=np.column_stack([Br,X[rows]])%P
        # RREF augmented with 45 equations and 35 RHS columns.
        for c in range(45):
            q=next(i for i in range(c,45) if AX[i,c])
            AX[[c,q]]=AX[[q,c]]
            if AX[c,c]==2: AX[c]=(2*AX[c])%P
            for i in range(45):
                if i!=c and AX[i,c]: AX[i]=(AX[i]-AX[i,c]*AX[c])%P
        C=AX[:,45:]%P
        out.append(C[10:,:])
    return out

ns1=runpy.run_path(str(ROOT/'research'/'phase2_1_invariant_space_verification_2026-09-15.py'))
A=[np.array(x,dtype=np.int64)%P for x in ns1['action_matrices']]
G=[np.array(x,dtype=np.int64)%P for x in ns1['gens']]
ns3=runpy.run_path(str(ROOT/'research'/'phase2_3_endH_optimized_2026-09-15.py'))
N=np.array(ns3['N'],dtype=np.int64)%P
E=quotient_action(A,N)

# First structural probe: fixed vectors of the five generators.
stack=np.vstack([((g-np.eye(35,dtype=np.int64))%P) for g in E])
fixed=null_basis(stack)

print('PHASE 2-13 / DIRECT STRUCTURAL PROBE OF E')
print('dim E = 35')
print('dim E^H =',len(fixed))
print('E^H = 0' if len(fixed)==0 else 'NONZERO INVARIANT SPACE')

# Probe cyclic submodules generated by each fixed vector candidate if any.
# If none exists, this is itself informative: E has no trivial submodule.
# More detailed root-vector analysis will be added only after this baseline is
# established, so that candidate choices are not smuggled in by hand.
assert len(fixed)==0
print('CERTIFICATE: E has no H-fixed vector.')
print('NEXT: compute positive-root/maximal-vector candidates using a fixed Borel.')
