"""Phase 2-8B: exact irreducibility certificate for M.

Instead of constructing an external ATLAS 25D module, compute the associative
F_3-algebra generated by the five exact 25x25 matrices describing the H=Sp4(F3)
action on M=ker(N)/im(N). If that algebra has dimension 25^2=625, then it is
End_F3(M), so M is irreducible (indeed absolutely irreducible).

This avoids the previous Phase 2-8 memory bottleneck in GAP's group-isomorphism
construction. The calculation is independent of ATLAS and of any chosen
intertwiner.

The identification with L(2,1) is then a separate literature/classification
step: the literature records that the 25-dimensional irreducible representation
of Sp4(F3) factoring through PSp4(3) is unique (and is defined over F3).
"""
from pathlib import Path
import runpy
import subprocess
import numpy as np

P=3
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'artifacts'/'phase2_8_B_irreducibility'
OUT.mkdir(parents=True, exist_ok=True)

ns=runpy.run_path(str(ROOT/'research/phase2_7_M_quotient_2026-09-15.py'))
MA=[np.array(x,dtype=np.int64)%P for x in ns['MA']]
assert len(MA)==5 and all(x.shape==(25,25) for x in MA)

# GAP matrix literal. This is only a transport format; the matrices themselves
# are exactly those produced by Phase 2-7.
def gap_matrix(A):
    rows=','.join('['+','.join(str(int(x)) for x in row)+']' for row in A)
    return f'Matrix(GF(3),[{rows}])'

gens='['+','.join(gap_matrix(A) for A in MA)+']'
gapfile=OUT/'check_algebra.g'
gapfile.write_text(f'''F:=GF(3);;
Gens:={gens};;
A:=Algebra(F,Gens);;
Print("NUMBER_OF_GENERATORS=",Length(Gens),"\\n");;
Print("ALGEBRA_DIMENSION=",Dimension(A),"\\n");;
Print("EXPECTED_FULL_END_DIMENSION=625\\n");;
QUIT;
''',encoding='utf-8')

# GAP is used only for the 25x25 associative algebra calculation; no group
# isomorphism, AtlasRep lookup, or large permutation representation is built.
proc=subprocess.run(['gap','-q','-m','1g',str(gapfile)],capture_output=True,text=True)
print(proc.stdout,end='')
print(proc.stderr,end='')
if proc.returncode:
    raise SystemExit(proc.returncode)

lines=proc.stdout.splitlines()
dim_line=next((x for x in lines if x.startswith('ALGEBRA_DIMENSION=')),None)
if dim_line is None:
    raise RuntimeError('GAP did not return ALGEBRA_DIMENSION')
dim=int(dim_line.split('=',1)[1])

full=(dim==625)
print('PHASE 2-8B / exact irreducibility certificate for M')
print('dim M = 25')
print('number of H generators = 5')
print('dim associative algebra generated by M-action =',dim)
print('dim End_F3(M) = 625')
print('M irreducible over F3 =',full)
print('CONCLUSION:', 'M IS IRREDUCIBLE' if full else 'irreducibility NOT proved')

(OUT/'result.txt').write_text('\n'.join([
    'Phase 2-8B exact irreducibility certificate',
    'DIM_M=25',
    'ALGEBRA_DIMENSION='+str(dim),
    'END_DIMENSION=625',
    'IRREDUCIBLE='+str(full),
    'CONCLUSION='+('M IS IRREDUCIBLE' if full else 'IRREDUCIBILITY NOT PROVED'),
])+'\n',encoding='utf-8')
