import runpy
import numpy as np
from itertools import product

P = 3
ROOT = 'research/'

# Reuse the already verified A3-4-11 computation.
ns = runpy.run_path(ROOT + 'phase2_24_A3_4_11_L5_obstruction_compression_2026-09-16.py')
ns1 = runpy.run_path(ROOT + 'phase2_1_invariant_space_verification_2026-09-15.py')

rank3 = ns['rank3']
vec4 = ns['vec4']
R4_matrix = np.array(ns['R4_matrix'], dtype=np.int64) % P
L5_basis = np.array(ns['L5_basis'], dtype=np.int64) % P
L5_rows = ns['L5_rows']
L5_left_inv = np.array(ns['L5_left_inv'], dtype=np.int64) % P
D_L5 = np.array(ns['D_L5'], dtype=np.int64) % P
rank_D_L5 = int(ns['rank_D_L5'])
words5 = ns['words5']
index5 = ns['index5']
X = ns1['X']
L2 = ns1['L2']
R = ns1['R']


def coords_many(V):
    V = np.array(V, dtype=np.int64) % P
    if V.ndim == 1:
        V = V[:, None]
    C = (L5_left_inv @ V[L5_rows, :]) % P
    assert np.array_equal((L5_basis @ C) % P, V)
    return C


def bracket(A, B):
    return ns1['bracket'](A, B)


def vec5(A):
    v = np.zeros(1024, dtype=np.int64)
    for w, c in A.items():
        v[index5[w]] = int(c) % P
    return v

# ------------------------------------------------------------
# Degree-5 Lie ideal generated by the quadratic relation R.
# For a homogeneous ideal generated by R in degree 2:
# (R)_5 = [L_1,(R)_4] + [L_2,(R)_3] + [L_3,R].
# ------------------------------------------------------------

R3_candidates = [bracket(R, x) for x in X]
R3_matrix = np.column_stack([ns1['vec4'](a)[:64] if False else vec5({}) for a in []]) if False else None

# Degree-3 word basis and vectorization.
words3 = list(product((1, 2, 3, 4), repeat=3))
index3 = {w: i for i, w in enumerate(words3)}

def vec3(A):
    v = np.zeros(64, dtype=np.int64)
    for w, c in A.items():
        v[index3[w]] = int(c) % P
    return v

R3_matrix = np.column_stack([vec3(a) for a in R3_candidates]) % P
assert rank3(R3_matrix) == 4

# L3 is spanned by [L2,L1].  Select an actual independent basis.
L3_candidates = [bracket(a, x) for a in L2 for x in X]
L3_matrix = np.column_stack([vec3(a) for a in L3_candidates]) % P
assert rank3(L3_matrix) == 20

L3_basis = []
r = 0
for j in range(L3_matrix.shape[1]):
    cols = L3_matrix[:, :j+1]
    if rank3(cols) > r:
        L3_basis.append(L3_candidates[j])
        r += 1
        if r == 20:
            break
assert r == 20

# A generic degree-5 bracket vector.
def bracket5(A, B):
    return vec5(bracket(A, B))

# ------------------------------------------------------------
# Cross-check the two independent 5-column bases of (R)_4.
# Among the six 5-subsets of the six displayed generators, exactly
# the subsets omitting column 0 or column 5 are independent.
# ------------------------------------------------------------

def independent_column_indices(M):
    M = np.array(M, dtype=np.int64) % P
    selected = []
    current = np.empty((M.shape[0], 0), dtype=np.int64)
    r = 0
    for j in range(M.shape[1]):
        candidate = np.column_stack([current, M[:, j]])
        nr = rank3(candidate)
        if nr > r:
            selected.append(j)
            current = candidate
            r = nr
    return selected, current

r4_indices_greedy, R4_ind_greedy = independent_column_indices(R4_matrix)
assert r4_indices_greedy == [0, 1, 2, 3, 4]

# The alternative independent basis is columns 1..5.
alt_indices = [1, 2, 3, 4, 5]
R4_ind_alt = R4_matrix[:, alt_indices]
assert rank3(R4_ind_alt) == 5


def local_span_from_R4_basis(R4_ind):
    cols = []
    for j in range(R4_ind.shape[1]):
        # R4_ind is in degree-4 associative coordinates.  Recover the
        # degree-4 Lie element as a dictionary, then bracket with X_i.
        a = {}
        # words4 is supplied by phase2_1.
        for i, w in enumerate(ns1['words4']):
            c = int(R4_ind[i, j]) % P
            if c:
                a[w] = c
        for x in X:
            cols.append(bracket5(a, x))
    M = np.column_stack(cols) % P
    return M

local_greedy = local_span_from_R4_basis(R4_ind_greedy)
local_alt = local_span_from_R4_basis(R4_ind_alt)
assert rank3(local_greedy) == 20
assert rank3(local_alt) == 20
assert rank3(np.column_stack([local_greedy, local_alt])) == 20

# ------------------------------------------------------------
# Assemble the other two degree-5 pieces.
# ------------------------------------------------------------

# [L2,(R)_3]
mid_candidates = []
for a in L2:
    for b in R3_candidates:
        mid_candidates.append(bracket5(a, b))
mid_matrix = np.column_stack(mid_candidates) % P

# [L3,R]
last_candidates = [bracket5(a, R) for a in L3_basis]
last_matrix = np.column_stack(last_candidates) % P

# Full (R)_5 in the ambient associative degree-5 space.
full_R5_matrix = np.column_stack([local_greedy, mid_matrix, last_matrix]) % P
full_R5_rank = rank3(full_R5_matrix)

assert full_R5_rank <= 64
assert full_R5_rank == rank3(np.column_stack([local_alt, mid_matrix, last_matrix]))

# Each generator block of D_L5 is in L5.  Therefore the natural
# relation subspace in the obstruction target L5^4 is (R)_5^4.
full_R5_L5 = coords_many(full_R5_matrix)
assert full_R5_L5.shape == (204, full_R5_matrix.shape[1])
assert rank3(full_R5_L5) == full_R5_rank

full_R5_L5_4 = np.zeros((4 * 204, 4 * full_R5_L5.shape[1]), dtype=np.int64)
for g in range(4):
    full_R5_L5_4[g*204:(g+1)*204, g*full_R5_L5.shape[1]:(g+1)*full_R5_L5.shape[1]] = full_R5_L5

full_R5_4_rank = rank3(full_R5_L5_4)
assert full_R5_4_rank == 4 * full_R5_rank

combined_rank = rank3(np.column_stack([D_L5, full_R5_L5_4]))
intersection_dim = rank_D_L5 + full_R5_4_rank - combined_rank
assert 0 <= intersection_dim <= min(rank_D_L5, full_R5_4_rank)

# ------------------------------------------------------------
# Output
# ------------------------------------------------------------
print('PHASE 2-25 / A3-4-11 FULL DEGREE-5 RELATION IDEAL')
print('dim (R)_3 =', rank3(R3_matrix))
print('dim L3 =', rank3(L3_matrix))
print('greedy independent (R)_4 columns =', r4_indices_greedy)
print('alternative independent (R)_4 columns =', alt_indices)
print('dim [L1,(R)_4] =', rank3(local_greedy))
print('dim [L2,(R)_3] =', rank3(mid_matrix))
print('dim [L3,R] =', rank3(last_matrix))
print('dim full (R)_5 =', full_R5_rank)
print('cross-basis full (R)_5 rank agreement =', rank3(np.column_stack([local_alt, mid_matrix, last_matrix])) == full_R5_rank)
print('dim (R)_5^4 in L5^4 =', full_R5_4_rank)
print('dim obstruction image =', rank_D_L5)
print('intersection dim(obstruction image, (R)_5^4) =', intersection_dim)
print('rank(obstruction + (R)_5^4) =', combined_rank)
print('OBSTRUCTION_DISJOINT_FROM_FULL_RELATION_IDEAL =', intersection_dim == 0)
print('RESULT: full degree-5 relation ideal assembled from all three homogeneous pieces.')
print('CAUTION: because the obstruction target is L5^4, the comparison is with (R)_5^4 componentwise.')
print('ALL A3-4-11 FULL RELATION CHECKS COMPLETED')
