"""Q3/Q9 Gate C-2b — H-equivariance of the restricted-power realization.

Purpose:
  Audit whether the fixed H-action used in the repository is an algebra
  automorphism on the associative/Magnus realization, and explicitly verify
  restricted-power compatibility on basis and mixed degree-1 elements.

Convention:
  H is generated by the five fixed symplectic transvections from
  03_CONVENTIONS_AND_IMPLEMENTATION.md.  Column action is used: the j-th
  column of A is the image of X_j.  The induced action on the free
  associative algebra is substitution, hence multiplication-preserving.

For degree-1 x, the restricted-power realization is x^[3] = x^3 in the
universal enveloping algebra.  We test:
    h(x^[3]) = (h x)^[3]
and, twice,
    h((x^[3])^[3]) = ((h x)^[3])^[3].

The mixed tests are important in characteristic 3: p-power is not a linear
map on sums, so X_i + c X_j tests the Jacobson/cross-term behavior.

This is an equivariance audit only. It does not define d_9^(9), establish
canonicality, or run N/J.
"""

P = 3
TRUNC = 9

def add(*As):
    out = {}
    for A in As:
        for w, c in A.items():
            c = (out.get(w, 0) + c) % P
            if c:
                out[w] = c
            elif w in out:
                del out[w]
    return out

def scale(A, c):
    c %= P
    return {w: (c*v) % P for w, v in A.items() if (c*v) % P}

def mul(A, B):
    out = {}
    for wa, ca in A.items():
        for wb, cb in B.items():
            w = wa + wb
            if len(w) <= TRUNC:
                c = (out.get(w, 0) + ca*cb) % P
                if c:
                    out[w] = c
                elif w in out:
                    del out[w]
    return out

def power(A, k):
    out = {(): 1}
    for _ in range(k):
        out = mul(out, A)
    return out

def fmt(A):
    return ", ".join(f"{w}:{c}" for w,c in sorted(A.items())) or "0"

# Authoritative symplectic form and five generating vectors.
J = [
    [0,1,0,0],
    [-1,0,0,0],
    [0,0,0,1],
    [0,0,-1,0],
]
GEN_V = [
    (1,0,0,0),
    (0,1,0,0),
    (0,0,1,0),
    (0,0,0,1),
    (1,0,1,0),
]

def mat_vec(A, x):
    return [sum(A[i][j]*x[j] for j in range(4)) % P for i in range(4)]

def transpose(A):
    return [list(row) for row in zip(*A)]

def mat_mul(A,B):
    return [
        [sum(A[i][k]*B[k][j] for k in range(4)) % P for j in range(4)]
        for i in range(4)
    ]

def transvection(v):
    # t_v = I + v (Jv)^T, as fixed by the repository convention.
    Jv = [sum(J[i][j]*v[j] for j in range(4)) % P for i in range(4)]
    A = [[1 if i == j else 0 for j in range(4)] for i in range(4)]
    for i in range(4):
        for j in range(4):
            A[i][j] = (A[i][j] + v[i]*Jv[j]) % P
    return A

GENS = [transvection(v) for v in GEN_V]

def lie_degree1_vector(x):
    return {(i+1,): x[i] % P for i in range(4) if x[i] % P}

def action_on_word_algebra(A, elem):
    # j-th column of A is h(X_j).
    images = []
    for j in range(4):
        images.append({(i+1,): A[i][j] for i in range(4) if A[i][j] % P})
    out = {(): 1}
    for w, coeff in elem.items():
        term = {(): 1}
        for letter in w:
            term = mul(term, images[letter-1])
        out = add(out, scale(term, coeff))
    return out

def symplectic_check(A):
    return mat_mul(mat_mul(transpose(A), J), A) == [[v % P for v in row] for row in J]

# Test set: all four basis vectors, plus X_i + c X_j for every i<j and c=1,2.
TEST_VECS = [(1 if k == i else 0 for k in range(4)) for i in range(4)]
TEST_VECS = [tuple(v) for v in TEST_VECS]
for i in range(4):
    for j in range(i+1,4):
        for c in (1,2):
            v = [0]*4
            v[i] = 1
            v[j] = c
            TEST_VECS.append(tuple(v))

assert all(symplectic_check(A) for A in GENS)

basis_pass = True
mixed_pass = True
iterated_pass = True
cases = 0
mixed_cases = 0

for A in GENS:
    for xvec in TEST_VECS:
        x = lie_degree1_vector(xvec)
        hx_vec = mat_vec(A, xvec)
        hx = lie_degree1_vector(hx_vec)

        # First p-power equivariance.
        lhs1 = action_on_word_algebra(A, power(x, 3))
        rhs1 = power(hx, 3)
        ok1 = lhs1 == rhs1
        basis_pass &= ok1
        cases += 1

        # Iterated p-power equivariance: degree 9.
        lhs9 = action_on_word_algebra(A, power(power(x, 3), 3))
        rhs9 = power(power(hx, 3), 3)
        ok9 = lhs9 == rhs9
        iterated_pass &= ok9

        if any(xvec[k] and sum(1 for z in xvec if z) > 1 for k in range(4)):
            mixed_cases += 1
            mixed_pass &= ok1

print("Q3/Q9 GATE C-2b — H-EQUIVARIANCE OF RESTRICTED-POWER REALIZATION")
print("field: F_3")
print("H generators: 5 fixed symplectic transvections")
print("action: column action; j-th column of A is h(X_j)")
print("associative realization: h is tested by multiplicative substitution")
print("test vectors:", len(TEST_VECS))
print("first p-power cases:", cases)
print("mixed-sum cases:", mixed_cases)
print("symplectic generator checks =", "PASS" if all(symplectic_check(A) for A in GENS) else "FAIL")
print("FIRST_P_EQUIVARIANCE =", "PASS" if basis_pass else "FAIL")
print("MIXED_SUM_JACOBSON_PREFLIGHT =", "PASS" if mixed_pass else "FAIL")
print("ITERATED_P_EQUIVARIANCE_DEGREE_9 =", "PASS" if iterated_pass else "FAIL")

assert basis_pass
assert mixed_pass
assert iterated_pass

print("C-2b RESULT = PASS")
print("SCOPE = H-equivariance audit of the associative/enveloping realization;")
print("        no canonical q=9 source, no d_9^(9), no N/J")
