"""Q3/Q9 S9 — explicit H-action bridge audit for the baseline target.

Purpose:
  Close the logical gap in the previous source-map target-action audit:
      g^T J g = J
          -> g.R2 = R2
          -> h(I_infty) = I_infty
          -> Q9^infty has the induced H-action.

The previous audit verified symplectic preservation and cited the coefficient
matrix rule, but did not directly execute g.R2 = R2 using the repository's
authoritative action implementation.

This audit:
  1. imports the authoritative five generators and apply_linear_map from
     phase2_1_invariant_space_verification_2026-09-15.py;
  2. constructs R2 explicitly in the associative realization;
  3. directly checks h(R2) = R2 for every authoritative generator;
  4. checks the previously audited restricted-power / multiplicative action
     compatibility on the same generators;
  5. records the exact structural implication that the smallest restricted
     ideal generated by R2 is H-stable.

This is an action-definition bridge audit, not a new q=9 relation-space
construction and not a q=3/q=infinity invariant test.
"""

import runpy

P = 3

ns = runpy.run_path(
    "research/phase2_1_invariant_space_verification_2026-09-15.py"
)
gens = ns["gens"]
apply_linear_map = ns["apply_linear_map"]

# R2 = [X1,X2] + [X3,X4] in the associative realization.
R2 = {
    (1, 2): 1,
    (2, 1): 2,
    (3, 4): 1,
    (4, 3): 2,
}

X = [{(i + 1,): 1} for i in range(4)]


def add(A, B):
    out = dict(A)
    for w, c in B.items():
        v = (out.get(w, 0) + c) % P
        if v:
            out[w] = v
        elif w in out:
            del out[w]
    return out


def scale(A, c):
    return {w: (c * v) % P for w, v in A.items() if (c * v) % P}


def mul(A, B):
    out = {}
    for wa, ca in A.items():
        for wb, cb in B.items():
            w = wa + wb
            c = (out.get(w, 0) + ca * cb) % P
            if c:
                out[w] = c
            elif w in out:
                del out[w]
    return out


def power(A, n):
    out = {(): 1}
    for _ in range(n):
        out = mul(out, A)
    return out


def action(g, A):
    return apply_linear_map(A, g)


def fmt(A):
    return ", ".join(f"{w}:{c}" for w, c in sorted(A.items())) or "0"


print("Q3/Q9 S9 — BASELINE H-STABILITY ACTION-BRIDGE AUDIT")
print("======================================================")
print("ACTION SOURCE = phase2_1_invariant_space_verification_2026-09-15.py")
print("GENERATOR COUNT =", len(gens))
print("R2 =", fmt(R2))

assert len(gens) == 5

# Direct implementation check: h.R2 == R2.
r2_fixed = []
for i, g in enumerate(gens):
    image = action(g, R2)
    ok = image == R2
    r2_fixed.append(ok)
    print(f"GENERATOR {i}: g.R2 == R2 ->", "PASS" if ok else "FAIL")
    if not ok:
        print("  image =", fmt(image))

assert all(r2_fixed)

# Same authoritative action: explicit multiplicativity and p-power
# compatibility on the degree-1 basis. C-2b already audits these facts
# more broadly; this local repetition pins the implication to the exact
# action object used above.
multiplicative = True
p_equivariant = True

for i, g in enumerate(gens):
    for a in X:
        for b in X:
            lhs = action(g, mul(a, b))
            rhs = mul(action(g, a), action(g, b))
            multiplicative &= (lhs == rhs)

    for x in X:
        lhs = action(g, power(x, 3))
        rhs = power(action(g, x), 3)
        p_equivariant &= (lhs == rhs)

print("AUTHORITATIVE ACTION MULTIPLICATIVITY =", "PASS" if multiplicative else "FAIL")
print("AUTHORITATIVE FIRST P-POWER EQUIVARIANCE =", "PASS" if p_equivariant else "FAIL")

assert multiplicative
assert p_equivariant

print()
print("STRUCTURAL IMPLICATION:")
print("  each authoritative generator fixes R2 exactly;")
print("  the same action preserves multiplication and restricted p-power;")
print("  therefore the smallest restricted ideal <R2>_res is preserved by")
print("  every generator, hence by H.")
print("  Consequently Q9^infty = L9^res/(I_infty)_9 has a well-defined")
print("  induced H-action.")
print()
print("RESULT = PASS / EXPLICIT ACTION-BRIDGE CLOSED")
print("BOUNDARY = this does not test q=9 relation-space H-stability,")
print("           D9, q=3/q=infinity distinction, or orientation recovery.")
