"""C3.1 — H-orbit closure of S9 in the degree-9 p-layer.

Purpose:
  Determine the exact H-span of S9 = X1^[9] in L1^[9] under the
  frozen H=Sp4(F3) action.

This is a dimension/closure gate only. It does NOT assert that the
H-orbit elements are relations of the fixed presentation
  x1^9 [x1,x2][x3,x4] = 1.
That provenance question is C3.2.

Frozen inputs:
  S9 = X1^[9] != 0
  L1^[9] has coefficient space F3^4
  H = Sp4(F3), generated by the repository's fixed transvections
  baseline intersection with L1^[9] = 0.

Decision:
  C3.1 PASS if complete orbit closure is internally consistent and
  yields the exact H-span dimension.
"""

P=3
J=[
    [0,1,0,0],
    [2,0,0,0],
    [0,0,0,1],
    [0,0,2,0],
]

def matvec(A,x):
    return [sum(A[i][j]*x[j] for j in range(4))%P for i in range(4)]

def transvection(v):
    Jv=matvec(J,v)
    return [[((1 if i==j else 0)+v[i]*Jv[j])%P for j in range(4)]
            for i in range(4)]

def rank3(rows, n=4):
    A=[[z%P for z in row] for row in rows]
    r=0
    for c in range(n):
        piv=next((i for i in range(r,len(A)) if A[i][c]),None)
        if piv is None:
            continue
        A[r],A[piv]=A[piv],A[r]
        inv=1 if A[r][c]==1 else 2
        A[r]=[(z*inv)%P for z in A[r]]
        for i in range(len(A)):
            if i!=r and A[i][c]:
                a=A[i][c]
                A[i]=[(u-a*v)%P for u,v in zip(A[i],A[r])]
        r+=1
    return r

def closure(gens, seed):
    basis=[seed[:]]
    changed=True
    while changed:
        changed=False
        old=basis[:]
        for v in old:
            for g in gens:
                w=matvec(g,v)
                if rank3(basis+[w])>len(basis):
                    basis.append(w)
                    changed=True
    return basis

def main():
    # The four coordinate transvections are enough for the closure test.
    # Use all four basis vectors as transvection parameters.
    gens=[transvection([1,0,0,0]),
          transvection([0,1,0,0]),
          transvection([0,0,1,0]),
          transvection([0,0,0,1])]

    # Symplectic sanity.
    for g in gens:
        JT=[[J[j][i]%P for j in range(4)] for i in range(4)]
        gj=[[sum(g[i][k]*J[k][j] for k in range(4))%P for j in range(4)] for i in range(4)]
        gjgt=[[sum(gj[i][k]*g[j][k] for k in range(4))%P for j in range(4)] for i in range(4)]
        assert gjgt==J

    s9=[1,0,0,0]
    orbit_span=closure(gens,s9)

    # The orbit span is contained in the 4D p-layer by construction.
    r=rank3(orbit_span)
    assert r==4

    # Verify that the coordinate basis is recovered.
    coordinate_basis=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]]
    assert rank3(orbit_span+coordinate_basis)==4

    # Frozen S9-B structural lemma:
    # baseline has zero intersection with L1^[9].
    baseline_l1_intersection=0
    assert baseline_l1_intersection==0

    print("C3.1 S9 H-ORBIT CLOSURE — 2026-09-19")
    print("======================================")
    print("seed S9 coefficient vector          =", s9)
    print("number of generator transvections  =", len(gens))
    print("complete orbit-span rank            =", r)
    print("ambient L1^[9] dimension            =", 4)
    print("baseline ∩ L1^[9] dimension        =", baseline_l1_intersection)
    print()
    print("RESULT: dim span(H·S9) = 4.")
    print("RESULT: span(H·S9) = L1^[9].")
    print("RESULT: C3.1 = PASS.")
    print("BOUNDARY: this does NOT establish that X2^[9], X3^[9], X4^[9]")
    print("          are relations of the fixed q=9 presentation.")
    print("NEXT: C3.2 provenance test.")

if __name__=="__main__":
    main()
