"""Q3/Q9 degree-9 source-map target-action audit — 2026-09-19.

Checks:
1. Every nonzero-vector symplectic transvection for the frozen J preserves J.
2. Therefore the quadratic relation R2, whose coefficient matrix is J,
   is fixed by the H generators.
3. The restricted ideal generated by R2 is therefore H-stable, so the
   frozen baseline quotient Q9^infty carries the induced H-action.
4. S9 is nonzero modulo the baseline by the closed S9-B structural lemma.
5. The target is constructed from the baseline only; no S9 is inserted.
"""

from itertools import product

P = 3
J = [
    [0,1,0,0],
    [2,0,0,0],
    [0,0,0,1],
    [0,0,2,0],
]

def mm(A, B):
    return [[sum(A[i][k]*B[k][j] for k in range(4)) % P
             for j in range(4)] for i in range(4)]

def mv(A, v):
    return [sum(A[i][j]*v[j] for j in range(4)) % P for i in range(4)]

def transpose(A):
    return [list(x) for x in zip(*A)]

def transvection(v):
    Jv = mv(J, v)
    return [[((1 if i == j else 0) + v[i]*Jv[j]) % P
             for j in range(4)] for i in range(4)]

def main():
    I = [[1 if i == j else 0 for j in range(4)] for i in range(4)]
    vectors = [v for v in product(range(P), repeat=4) if any(v)]
    generators = [transvection(list(v)) for v in vectors]

    assert len(generators) == 80
    assert all(mm(mm(g, J), transpose(g)) == J for g in generators)
    assert all(mm(mm(transpose(g), J), g) == J for g in generators)

    # R2 = X1X2-X2X1+X3X4-X4X3 has coefficient matrix J.
    # Under the frozen column action, coefficient matrices transform as
    # J -> g^T J g, hence R2 is fixed by every generator.
    assert all(mm(mm(transpose(g), J), g) == J for g in generators)

    e1 = [1,0,0,0]
    e2 = [0,1,0,0]
    witness = transvection(e2)
    assert mv(witness, e1) == [1,1,0,0]

    print("Q3/Q9 SOURCE-MAP TARGET-ACTION AUDIT — 2026-09-19")
    print("================================================")
    print("nonzero-vector transvections checked =", len(generators))
    print("all generators preserve J =", True)
    print("R2 coefficient matrix fixed =", True)
    print("t_e2(e1) =", mv(witness, e1))
    print("DECISION: baseline restricted ideal is H-stable.")
    print("DECISION: Q9^infty carries a well-defined induced H-action.")
    print("SOURCE: S9 -> [S9] is nonzero by S9-B.")
    print("BOUNDARY: no q=9 relation insertion; no degree-3 N/J reuse.")

if __name__ == "__main__":
    main()
